# Generated by Django 4.0.5 on 2022-06-22 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='view_news',
            new_name='views',
        ),
        migrations.AddField(
            model_name='news',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.city'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(upload_to='news/'),
        ),
    ]
