# Generated by Django 4.0.5 on 2022-06-22 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_category_options_alter_news_options_news_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='created_at',
            new_name='created',
        ),
    ]
